default: &default
  adapter: postgresql
  encoding: utf8
  pool: 50
  timeout: 5000
  host: localhost

development:
  <<: *default
  database: onlinepay_psp
  username: dengchao
  password: 19681009

production:
  <<: *default
  database: onlinepay_psp_pro
  username: postgres
  password: xiaozhu
