# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19115cf0cbc153ef62455df9694076a3f021391bd86edff6575336e91ac9eda0f12a1880d3af6c8cf04bd6d85437e34b0708c1a83885fe4ed0bb5ba370e301b6

test:
  secret_key_base: f2c42609695d6321d2ed54c40b83191039010da5333b0fb1b9304f9f30f7117b8466e583828802a992c1d5ed124f5c59dcf60a80766db9dd972e6b620d467fe6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: a6d4a5899a04d6b4a94c97f98c29fc4ee5d2f4c435d8cf72e3de4383b920cfdd6a376c3293fd6d5031d6b7fce38adcd1b2c676809ca20ece6d8076c4542672db
